name: neds
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  # State Managment
  get: ^4.3.8
  get_storage: ^2.0.3

  # Utilities
  flutter_svg: ^0.22.0
  cached_network_image: ^3.2.0
  multi_image_picker2: ^5.0.2
  google_fonts: ^2.1.0
  url_launcher: ^6.0.18
  path_provider: ^2.0.8
  image_picker: ^0.8.5+3
  speech_to_text: ^5.6.0
  avatar_glow: ^2.0.2
  permission_handler: ^9.2.0
  flutter_speed_dial: ^6.0.0
  grouped_list: ^5.1.2

  # Firebase
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13
  google_ml_kit: ^0.11.0

  # HTTP
  http: ^0.13.4

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/img/
    - assets/svg/
    - assets/ml/

  fonts:
    - family: Atma
      fonts:
        - asset: fonts/Atma-Bold.ttf
        - asset: fonts/Atma-Light.ttf
        - asset: fonts/Atma-Medium.ttf
        - asset: fonts/Atma-SemiBold.ttf
        - asset: fonts/Atma-Regular.ttf
